# -*- coding: utf-8 -*-mail_template
{
    'name': 'Project Entries',
    'category': 'Purchase',
    'version': '13.0',
    'sequence': 5,
    'summary': 'Project Entries',
    "website": "http://www.pptssolutions.com",
    "author": "PPTS [India] Pvt.Ltd.",
    'description': """
    """,
    'depends': ['base','purchase','mail','xs_purchase_advance_payment'],
    'data': [
        'security/project_entries_security.xml',
        'security/ir.model.access.csv',
        'report/quotation_report_inherited.xml',
        'report/closure_report_view.xml',
        'wizard/reject_reason_view.xml',
        'wizard/container_details_report_views.xml',
        'wizard/update_price_wizard_views.xml',
        'wizard/third_party_arrival_view.xml',
        'wizard/psm_report_view.xml',
        'wizard/incoming_shipment_report_view.xml',
        'wizard/outgoing_shipment_report_view.xml',
        'wizard/transport_popup_view.xml',
        'views/project_entries_views.xml',
        'views/purchase_views.xml',
        # 'views/account_move_views.xml',
        'report/report_action.xml',
        'report/logistics_request_report.xml',
        'report/mask_purchase_order_templete.xml',
        'data/mail_template.xml',
        'data/actual_sales_cost_cron.xml',
        
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
