# -*- coding: utf-8 -*-
{
    'name': 'Custom Inventory',
    'category': 'Inventory',
    'version': '13.0',
    'sequence': 5,
    'summary': 'Inventory Customization for Morphosis',
    "website": "http://www.pptssolutions.com",
    "author": "PPTS [India] Pvt.Ltd.",
    'description': """
    """,
    'depends': ['base', 'stock', 'ppts_project_entries', 'hr', 'mail', 'ppts_logistics','account'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'wizard/bsd_annexe7_report_view.xml',
        'wizard/bsd_update_view.xml',
        'wizard/annuxe_update_view.xml',
        'wizard/close_container_view.xml',
        'wizard/create_actions_view.xml',
        'wizard/load_container_view.xml',
        'wizard/load_truck_view.xml',
        'wizard/release_loaded_truck_views.xml',
        'wizard/release_truck_views.xml',
        'wizard/unload_containers_views.xml',
        'wizard/unload_truck_view.xml',
        'wizard/non_conformity_wizard_view.xml',
        'wizard/re_confirm_container_view.xml',
        'wizard/create_lead_rc_view.xml',
        'wizard/partially_selling_container_view.xml',
        'wizard/group_contaniers_view.xml',
        'wizard/create_bulk_container_view.xml',
        'wizard/update_transporter_details_view.xml',
        'wizard/rc_second_process_view.xml',
        'wizard/create_fractions_wizard.xml',
        'wizard/register_chronopost_view.xml',
        'wizard/update_chronopost_details_view.xml',
        'wizard/update_time_view.xml',
        'wizard/update_time_picking.xml',
        'wizard/update_initial_demand_wizard_view.xml',
        'wizard/update_purchase_order_view.xml',
        'wizard/stop_timer_wizard_view.xml',
        'wizard/close_fractions_view.xml',
	    'wizard/register_chronopost_bulk.xml',
        'wizard/update_time_reception.xml',
        'wizard/move_to_production_view.xml',
        'wizard/add_additional_product_view.xml',
        'wizard/update_stock_container_weight_view.xml',
        'wizard/stock_container_valuation.xml',
        'data/mail_template.xml',
        'data/cron_data.xml',
        'views/waste_type_view.xml',
        'views/containers_view.xml',
        'views/fractions_view.xml',
        'views/reusable_container_view.xml',
        'views/stock_picking_views.xml',
        'views/project_entries_view.xml',
        'views/purchase_order_view.xml',
        'views/stock_location_view.xml',
	    'views/stock_container_line.xml',
        'report/barcode_paper_format.xml',
        'report/container_barcode_report.xml',
        'report/container_barcode_template.xml',
        'views/configuration.xml',
        'views/fraction_template.xml',
        'views/account_move_inherit.xml',
        'report/report_action.xml',
        'report/picking_list_report.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
